### ISSUE TITLE
GNOME Software flags Text Pieces as unsafe

### ISSUE THREAD

**Issue by automerisnaranja** [liferooter/textpieces#129]
## Affected version
3.4.1 Flathub

## Description

GNOME Software labels Text Pieces as unsafe because it "can acquire abirtrary permissions":

![image](https://github.com/liferooter/textpieces/assets/127631126/6c7d757f-9b4d-417c-9e3b-7979a3199f1c)

Albeit this rating being a bit inconclusive sometimes, [which is something](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1451) that maintainers are aware, it's kinda demotivating to install Text Pieces after seeing this warning (especially for users that don't know what technical reasons cause this). I'm not sure if a fix for this is out of scope, though.

**Comment by liferooter** [comment]
Text Pieces requires permission to run arbitrary code on the host system. It's used to run custom tool scripts inside the host environment instead of the sandbox to allow user to use languages, packages and binaries from the system in the script and generally make the sandbox transparent. Unfortunately, this cannot be done using portals, so the only way is to make the application unsafe (grant it full indirect access to the system).
