### ISSUE TITLE
Is this repo still alive?

### ISSUE THREAD

**Issue by marcinjahn** [liferooter/textpieces#141]
I see there are a few hanging PRs. I wanted to add Base64Url encoder/decoder, but I'm not sure if that's even going to be merged.

**Comment by liferooter** [comment]
The situation is difficult. I've started rewritting the application from scratch last year. Unfortunately, I have a lot of things to do because of finishing school and then starting studying at university. Now I am trying to finish this huge update, but since my previous forecasts of finishing dates all failed, I can't really guarantee any certain time I'll finish it.

The existing repo is in some kind of hibernation, because I see no reasons to continue working on the previous version when I have to finish new one as soon as possible.

I work on the new version at https://gitlab.com/liferooter/textpieces-gnome.

The UI is mostly finished, but now I'm trying to implement typed parameters (in current terms, typed arguments). Unfortunately, I do not have too much time until I'll fully adapt to studying at university.

So no, this repo is not alive, but I still read the issues and consider them to be issues of the next version. When the new version will be finished, I'll archive this repository and put the link to the new one.

P.S. Please do not close the issue, I want people who also want to find out what's happening with the repo to see it.

**Comment by marcinjahn** [comment]
@liferooter I suggest to update readme with this information. Currently, in Contributions it says "Contributions are welcome.".

**Comment by liferooter** [comment]
Good idea!

**Comment by liferooter** [comment]
Fixed in Text Pieces 4.0, which will be released soon.

This repo is totally dead. New one... or, sorry, new two:
- **Core library:** https://gitlab.com/liferooter/textpieces
- **Application itself:** https://gitlab.com/liferooter/textpieces-gnome
