### ISSUE TITLE
How do I create a backup of my custom tools in a way that reinstalling Text Pieces will automatically pick up these tools

### ISSUE THREAD

**Issue by sylvester-roos** [liferooter/textpieces#144]
If such a thing is even possible, of course.

I could simply make a backup of `~/.local/share/textpieces/scripts/` but that would result in the loss of the metadata of the script in the case of a reinstallation, like the amount of parameters, the title, and the description.

**Comment by liferooter** [comment]
Well, I've used `~/.local/share/textpieces/scripts` because of a bug in portals that didn't allowed to open files in `~/.var/app/<APP ID>/` through portals. Currently, the bug is fixed, but Text Pieces is still stores its scripts inside `~/.local/share/textpieces`, but metadata is inside `~/.var/app/com.github.liferooter.textpieces/config/textpieces`.

**Comment by sylvester-roos** [comment]
Thanks!
