### ISSUE TITLE
flatpak update because org.gnome.Platform branch 44 is end-of-life

### ISSUE THREAD

**Issue by abdulalalalalala** [liferooter/textpieces#147]
current app flatpak build `build-aux/flatpak/com.github.liferooter.textpieces.yaml`:
```
runtime: org.gnome.Platform
runtime-version: '43'
```

warning from flatpak fedora:
```
The GNOME 44 runtime is no longer supported as of March 20, 2024
```

**Comment by liferooter** [comment]
The runtime wasn't updated because I took a long pause in development of the application right in the middle of [it's full rewrite](https://gitlab.com/liferooter/textpieces-gnome). Now the rewrite is finished and I'm trying to [publish the new version](https://github.com/flathub/flathub/pull/5201) on Flathub. The new version of course uses the latest runtime version. The old version is not supposed to get any more updates.

As a user, you just have to wait until the new version will be accepted. Flatpak will seamlessly replace the old version with the new one.
