### ISSUE TITLE
Text Pieces no longer follows the system color scheme

### ISSUE THREAD

**Issue by AbrarSL** [liferooter/textpieces#92]
It looks like implementing the recoloring feature unfortunately removed the system wide color scheme support. I was wondering whether this was a design decision or a bug?

**Comment by liferooter** [comment]
To be honest, I just was too lazy to reimplement `gtksourceview`'s theme chooser with feature of filtering. It _will_ be fixed.

**Comment by me6262** [comment]
any progress? i love this tool, it just sticks out like a sore thumb at the moment.

**Comment by liferooter** [comment]
I'm working on Text Pieces 4.0 which is complete rewrite of the application. Maybe I'll fix the issue in it.

**Comment by me6262** [comment]
I look forward to seeing the new version!

**Comment by amadeusp** [comment]
Also looking forward to the "follow system setting" option for the appearance. Excited for the 4.0 release. :nerd_face:

**Comment by amadeusp** [comment]
> I'm working on Text Pieces 4.0 which is complete rewrite of the application. Maybe I'll fix the issue in it.

Is there any news yet? :)

**Comment by liferooter** [comment]
Well, the rewrite was almost finished, but then I've got too frustrated by GTK, gtksourceview (library behind the editor view Text Pieces have), GNOME and the world itself and stopped working on it. Now I spend most of my time on studying at university and also trying to explore UI toolkit development and graphics rendering. So probably the new release will finished after one of the following events happens:

- Something happens with me and I come back to GTK and GNOME and finish the project.
- Someone creates a UI library I would like, so I rewrite new Text Pieces on it. It's even possible (but I don't think that it's likely) that this library will a new version of GTK.
- I begin to understand UI things behind UI rendering and create such library by myself.

Maybe I'm too perfectionistic and not responsible enough. But I just can't work with that hacky object-oriented imperative UI library full of legacy anymore. Yes, it's the best option available. But still I think that we really need something better than manually setting widget properties, implementing GObject subclasses for everything, working with three possible ways to implement shortcuts with different problems with each of them and so on. I also think that working on anything else before this problem is solved is a huge waste of my time. So I'm sorry, but I can promise nothing about the project :(

**Comment by liferooter** [comment]
> Well, the rewrite was almost finished, but then I've got too frustrated by GTK, gtksourceview (library behind the editor view Text Pieces have), GNOME and the world itself and stopped working on it. Now I spend most of my time on studying at university and also trying to explore UI toolkit development and graphics rendering. So probably the new release will finished after one of the following events happens:
> 
>     * Something happens with me and I come back to GTK and GNOME and finish the project.
> 
>     * Someone creates a UI library I would like, so I rewrite new Text Pieces on it. It's even possible (but I don't think that it's likely) that this library will a new version of GTK.
> 
>     * I begin to understand UI things behind UI rendering and create such library by myself.
> 
> 
> Maybe I'm too perfectionistic and not responsible enough. But I just can't work with that hacky object-oriented imperative UI library full of legacy anymore. Yes, it's the best option available. But still I think that we really need something better than manually setting widget properties, implementing GObject subclasses for everything, working with three possible ways to implement shortcuts with different problems with each of them and so on. I also think that working on anything else before this problem is solved is a huge waste of my time. So I'm sorry, but I can promise nothing about the project :(

Good news! I had some time working with C++ because of studying needs and now GTK doesn't look so awful to me because after C++ everything is beautiful and clean. So I probably will finish the new version in the near future :D

**Comment by amadeusp** [comment]
> > Well, the rewrite was almost finished, but then I've got too frustrated by GTK, gtksourceview (library behind the editor view Text Pieces have), GNOME and the world itself and stopped working on it. Now I spend most of my time on studying at university and also trying to explore UI toolkit development and graphics rendering. So probably the new release will finished after one of the following events happens:
> > ```
> > * Something happens with me and I come back to GTK and GNOME and finish the project.
> > 
> > * Someone creates a UI library I would like, so I rewrite new Text Pieces on it. It's even possible (but I don't think that it's likely) that this library will a new version of GTK.
> > 
> > * I begin to understand UI things behind UI rendering and create such library by myself.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe I'm too perfectionistic and not responsible enough. But I just can't work with that hacky object-oriented imperative UI library full of legacy anymore. Yes, it's the best option available. But still I think that we really need something better than manually setting widget properties, implementing GObject subclasses for everything, working with three possible ways to implement shortcuts with different problems with each of them and so on. I also think that working on anything else before this problem is solved is a huge waste of my time. So I'm sorry, but I can promise nothing about the project :(
> 
> Good news! I had some time working with C++ because of studying needs and now GTK doesn't look so awful to me because after C++ everything else looks beautiful and clean. So I probably will finish the new version in the near future :D

Good news indead! I am so happy to hear this! :+1:

**Comment by liferooter** [comment]
Fixed in Text Pieces 4.0, which will be released soon

**Comment by amadeusp** [comment]
> Fixed in Text Pieces 4.0, which will be released soon

Amazing news. Can't wait! Thanks a lot!
